# https://circleci.com/docs/2.0/language-javascript/
version: 2
jobs:
  'test_node_10':
    docker:
      - image: circleci/node:10
    working_directory: ~/lib
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
  'test_node_latest':
    docker:
      - image: circleci/node:latest
    working_directory: ~/lib
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
  'release':
    docker:
      - image: circleci/node:10
    working_directory: ~/lib
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - run: yarn semantic-release

workflows:
  version: 2
  test_and_release:
    jobs:
      - test_node_10
      - test_node_latest
      - release:
          requires:
            - test_node_10
            - test_node_latest
